plugins {
    id 'java'
}

group = 'by.koronatechshiftcourse'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.36'

    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}

jar {
    manifest {
        attributes 'Main-Class': 'by.koronatechshiftcourse.Runner'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}